### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by mathias3** [krapes/OCR_Receipt_Reading#1]
Traceback (most recent call last):
  File "OCR_Receipt_Reading/Main.py", line 649, in <module>
    clipsL = clip_letter(lines)
  File "OCR_Receipt_Reading/Main.py", line 484, in clip_letter
    heat_map = create_heat_map(boxes, clip)
  File "OCR_Receipt_Reading/Main.py", line 352, in create_heat_map
    heat_map[index] = -3 if reward <= -3 else reward
IndexError: list assignment index out of range

Process finished with exit code 1

**Comment by krapes** [comment]
Hi @mathias3  

Could you explain more about the input you were using when this error occurred?
Thanks
